"""Adicionando colunas country, latitude, longitude, windspeed, weather_condition, e precipitation

Revision ID: 90476e67ac81
Revises: c510318ae863
Create Date: 2024-12-01 11:07:11.087281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90476e67ac81'
down_revision = 'c510318ae863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))

    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('windspeed', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weather_condition', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('precipitation', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weather_data', schema=None) as batch_op:
        batch_op.drop_column('precipitation')
        batch_op.drop_column('weather_condition')
        batch_op.drop_column('windspeed')

    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
